// Knight's Puzzle — engine (pure, no DOM/React, deterministic).
//
// A puzzle is generated by walking a knight randomly (no revisits) on an n×n
// board. The visited squares become the playable level; everything else is
// removed. Because the level IS a real knight's walk, it is always solvable by
// construction — there is deliberately NO solver here.

export type Cell = { r: number; c: number };

export type Puzzle = {
  /** Board side length (n×n). */
  n: number;
  /** n×n grid, row-major: available[r][c] is true if the square is playable. */
  available: boolean[][];
  /** Where the knight begins (first cell of the witness path). */
  start: Cell;
  /** Where the knight must finish (last cell of the witness path). */
  end: Cell;
  /** The generator's witness solution: start..end, one entry per playable cell. */
  path: Cell[];
  /** Seed the puzzle was generated from (reproducibility). */
  seed: number;
};

// The 8 knight offsets (row, col).
const KNIGHT_DELTAS: ReadonlyArray<readonly [number, number]> = [
  [-2, -1],
  [-2, 1],
  [-1, -2],
  [-1, 2],
  [1, -2],
  [1, 2],
  [2, -1],
  [2, 1],
];

// How many candidate walks we try (deterministically) before giving up and
// returning the longest one found. All randomness is derived from the seed, so
// this stays fully reproducible.
const CANDIDATE_WALKS = 64;

/** In-board knight destinations from `cell` on an n×n board. */
export function knightMoves(cell: Cell, n: number): Cell[] {
  const moves: Cell[] = [];
  for (const [dr, dc] of KNIGHT_DELTAS) {
    const r = cell.r + dr;
    const c = cell.c + dc;
    if (r >= 0 && r < n && c >= 0 && c < n) moves.push({ r, c });
  }
  return moves;
}

/** Deterministic PRNG (mulberry32). Same seed → same stream of [0, 1) values. */
export function makeRng(seed: number): () => number {
  let a = seed >>> 0;
  return function next() {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function key(cell: Cell, n: number): number {
  return cell.r * n + cell.c;
}

function isKnightStep(a: Cell, b: Cell): boolean {
  const dr = Math.abs(a.r - b.r);
  const dc = Math.abs(a.c - b.c);
  return (dr === 1 && dc === 2) || (dr === 2 && dc === 1);
}

// One random non-revisiting knight walk of up to `maxSteps` moves.
function randomWalk(n: number, maxSteps: number, rng: () => number): Cell[] {
  const start: Cell = { r: Math.floor(rng() * n), c: Math.floor(rng() * n) };
  const path: Cell[] = [start];
  const visited = new Set<number>([key(start, n)]);
  let current = start;

  for (let step = 0; step < maxSteps; step++) {
    const options = knightMoves(current, n).filter(
      (m) => !visited.has(key(m, n)),
    );
    if (options.length === 0) break; // dead end — accept the shorter walk
    const next = options[Math.floor(rng() * options.length)];
    path.push(next);
    visited.add(key(next, n));
    current = next;
  }
  return path;
}

/**
 * Generate a puzzle on an n×n board.
 *
 * @param n     board side length (integer, n ≥ 3)
 * @param steps maximum number of knight MOVES (integer, steps ≥ 1). The path
 *              therefore has at most `steps + 1` cells. Clamped to `n*n - 1`.
 * @param seed  integer seed; the whole puzzle is a pure function of (n, steps, seed).
 *
 * Policy: try a fixed number of candidate walks (all from the seeded RNG); keep
 * the FIRST one that reaches the target length `min(steps + 1, n*n)`, otherwise
 * the longest found (first-longest tie-break). Fails explicitly if it cannot
 * produce a path of length ≥ 2.
 */
export function generatePuzzle(n: number, steps: number, seed: number): Puzzle {
  if (!Number.isInteger(n) || n < 3) {
    throw new Error(`n must be an integer >= 3 (got ${n})`);
  }
  if (!Number.isInteger(steps) || steps < 1) {
    throw new Error(`steps must be an integer >= 1 (got ${steps})`);
  }
  if (!Number.isInteger(seed)) {
    throw new Error(`seed must be an integer (got ${seed})`);
  }

  const maxSteps = Math.min(steps, n * n - 1);
  const targetCells = Math.min(steps + 1, n * n);

  const rng = makeRng(seed);
  let best: Cell[] = [];
  for (let attempt = 0; attempt < CANDIDATE_WALKS; attempt++) {
    const walk = randomWalk(n, maxSteps, rng);
    if (walk.length > best.length) best = walk; // strict > → first-longest wins
    if (best.length >= targetCells) break;
  }

  if (best.length < 2) {
    throw new Error(
      `could not generate a puzzle of length >= 2 for n=${n}, steps=${steps}, seed=${seed}`,
    );
  }

  const available: boolean[][] = Array.from({ length: n }, () =>
    new Array<boolean>(n).fill(false),
  );
  for (const cell of best) available[cell.r][cell.c] = true;

  return {
    n,
    available,
    start: best[0],
    end: best[best.length - 1],
    path: best,
    seed,
  };
}

/**
 * Knight moves from `current` that are playable and not yet visited.
 * Does NOT mutate `visited`.
 */
export function legalMoves(
  puzzle: Puzzle,
  current: Cell,
  visited: Iterable<Cell>,
): Cell[] {
  const seen = new Set<number>();
  for (const cell of visited) seen.add(key(cell, puzzle.n));
  return knightMoves(current, puzzle.n).filter(
    (m) => puzzle.available[m.r][m.c] && !seen.has(key(m, puzzle.n)),
  );
}

/** Total number of playable cells. */
function availableCount(puzzle: Puzzle): number {
  let count = 0;
  for (let r = 0; r < puzzle.n; r++) {
    for (let c = 0; c < puzzle.n; c++) {
      if (puzzle.available[r][c]) count++;
    }
  }
  return count;
}

/**
 * True iff `visited` is a winning sequence: it starts on start, ends on end,
 * each step is a knight move, every cell is playable, there are no duplicate
 * visits, and it covers exactly all playable cells.
 */
export function isWin(puzzle: Puzzle, visited: Cell[]): boolean {
  const n = puzzle.n;
  if (visited.length < 2) return false;

  const first = visited[0];
  const last = visited[visited.length - 1];
  if (first.r !== puzzle.start.r || first.c !== puzzle.start.c) return false;
  if (last.r !== puzzle.end.r || last.c !== puzzle.end.c) return false;

  if (visited.length !== availableCount(puzzle)) return false;

  const seen = new Set<number>();
  for (let i = 0; i < visited.length; i++) {
    const cell = visited[i];
    if (cell.r < 0 || cell.r >= n || cell.c < 0 || cell.c >= n) return false;
    if (!puzzle.available[cell.r][cell.c]) return false;
    const k = key(cell, n);
    if (seen.has(k)) return false; // duplicate visit
    seen.add(k);
    if (i > 0 && !isKnightStep(visited[i - 1], cell)) return false;
  }
  return true;
}
